runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
    http_headers:
      cache-control: no-store

  - url: /manifest.webmanifest
    http_headers:
      cache-control: no-store

    # All files with extensions are considered static
  - url: /(.+\..+)
    static_files: \1
    upload: (.*)
    secure: always

    # The rest are folders
  - url: /(.*)/
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
    http_headers:
      cache-control: no-store
  - url: /(.*)
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
    http_headers:
      cache-control: no-store

    # 404
  - url: /en/(.*)
    static_files: en/404.html
    upload: en/404.html
  - url: /(.*)
    static_files: 404.html
    upload: 404.html

error_handlers:
  - file: 404.html
